export const Strings = {
    passo_ecom: "Passo E-Commerce",
    empty_fav_list: "Favori Listeniz Boş",
    can_see_fav_part_when_add: "Beğendiklerinizi Favorilere Ekledikçe Burada Görebileceksiniz",
    empty_basket: "Sepetiniz Boş",
    can_see_basket_when_add: "Sepetinize Ürün Ekledikçe Burada Görebileceksiniz",
    back_to_homepage: "Anasayfaya Dön",
    total: "Toplam",
    delete: "Sil",
    tl: "₺",
    buy: "Satın Al",
    search: "Ara...",
    clean_search: "Aramayı Temizle",
    filter: "Filtrele",
    max_price: "En Yüksek Fiyat",
    min_price: "En Düşük Fiyat",
    filter_least_one_item: "En Az Bir Filtreleme Yapmalısınız!",
    enter_max_price: "Maksimum Değer Giriniz.",
    refuse: "Vazgeç",
    examine: "İncele",
    tl2: ".00 ₺",
    heart_emoji: "\u2764",
    empty_heart: "🤍",
    results_found: "Bulunan Sonuçlar",
    loading: "Loading...",
    cannot_found_product: "Ürün Bulunamadı..",
    try_a_different_search_term: "Farklı bir arama terimi deneyin",
    add_basket: "Sepete Ekle",
    favorites: "Favoriler",
    can_see_favs_after_add: "Beğendiklerinizi Favorilere Ekledikçe Burada Görebileceksiniz.",
    basket_emoji: "🛒",
    filter_emoji: "🔍",
    back: "◁ ",
    warning: "⚠️",
    clean: "Temizle"
}